<Project Sdk="Godot.NET.Sdk/4.7.2">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ValveKeyValue" Version="0.70.0.499" />
    <PackageReference Include="ValvePak" Version="5.0.2.177" />
    <PackageReference Include="ValveResourceFormat" Version="20.0.6980" />
  </ItemGroup>
</Project>